(in-package :cl-user)
; (pushnew :outsource *features*)
(pushnew :developer *features*)
(pushnew :appserver *features*)
;(pushnew :test-lexer-1s *features*) 
(defparameter *lisp-root* "c:/lisp/")
(defparameter *mail-password* "")
(defparameter *app-server-debug* 1)
(defparameter *developers-database-alias* "server03s:ripol-sales-4-dev")
(defparameter *developers-sklad-database-alias* "server002:ripol-sklad-dev")
(defparameter *websms-pass* "")
 
(setf *compile-print* 0)
(setf *compile-verbose* 0)